version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always
#TODO: add healthcheck

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
